Feat/frontend recommendation
snuhcs-course/swpp-2023-project-team-14 pull request #64
Opened 2023-11-20 15:36 UTC by yuri-0415

Finished recommendation feature 
* update UI
* update Logic

2023-11-21 05:44 UTC, SeongjunJo requested changes
리뷰 남긴 거 토대로 수정 부탁드립니다.
그리고 오늘 핸드폰 받으면 직접 앱 실행해보면서 여러 use cases 시도해보고 오류가 확실히 없을 때 다시 PR 남겨주세요

2023-11-21 05:44 UTC, SeongjunJo commented on frontend/app/src/main/java/com/example/haengsha/model/dataSource/AppContainer.kt
추천 기능은 홈화면에서 사용하는 API service랑 같이 묶여도 될 거 같아서, 따로 data repository를 만들 필요는 없을 것 같습니다. 나중에 수정하면 되겠어요

2023-11-21 05:44 UTC, SeongjunJo commented on frontend/app/src/main/java/com/example/haengsha/model/viewModel/event/RecommendationApiViewModel.kt
지금 catch 구문에서 exception 핸들링할 때 errorMassage 변수를 선언만 하고 사용하지 않고 있습니다. 에러 메세지를 보여줄 거면 UiState에서 object 대신 data class로 선언해서 message를 인자로 받던가, 홈 화면에서 따로 선언하고 보여주는 게 좋겠습니다.
그리고 IOException은 클라-서버간 네트워크 연결 문제라서, 단순히 '이벤트를 불러오지 못했습니다' 보다 '네트워크 연결을 확인해주세요'가 좋을 거 같습니다.

2023-11-21 05:44 UTC, SeongjunJo commented on frontend/app/src/main/java/com/example/haengsha/ui/screens/home/Home.kt
추천 행사를 받아오는 게 Home 화면이 리랜더링 될 때마다 호출되는데, 사용자가 추천 행사 보기를 누를 때만 호출해야 합니다.
지금 코드에서는 추천 행사 받아올 때 에러가 발생하면, 유저는 홈화면에 들어갔을 뿐인데 추천 행사를 못 받아왔다는 에러를 마주하게 됩니다.

2023-11-21 05:44 UTC, SeongjunJo commented on frontend/app/src/main/java/com/example/haengsha/ui/screens/home/TabView.kt
UiState에서 정의한 에러 핸들링 state를 사용하지 않고 있습니다. 이러면 에러가 발생했을 때 앱에 crash가 발생하진 않겠지만, 유저는 아무 안내도 없이 아무것도 없는 빈 화면을 보게 됩니다.

2023-11-23 06:21 UTC, yuri-0415 commented on frontend/app/src/main/java/com/example/haengsha/ui/screens/home/Home.kt
추천행사가 tab 이동과 관계 없이 하나만 있어서 한번 불러오는게 낫지 않을까 했습니다! Home 화면에서 한번 불러오고, 유저가 여러 tab을 이동해도 같은 내용을 띄워주는거니까 이런 식으로 처리했는데, 서버 부하가 심한게 아니라면 현 방식을 유지하면 어떨까요?

2023-11-23 07:14 UTC, SeongjunJo commented
그냥 머지하고 바로 고쳐서 푸쉬 하겠습니다.

2023-11-23 07:14 UTC, merged